# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.export_template import ExportTemplate  # noqa: E501
from aionetbox.rest import ApiException


class TestExportTemplate(unittest.TestCase):
    """ExportTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportTemplate(self):
        """Test ExportTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.export_template.ExportTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
