# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.nested_power_port import NestedPowerPort  # noqa: E501
from aionetbox.rest import ApiException


class TestNestedPowerPort(unittest.TestCase):
    """NestedPowerPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNestedPowerPort(self):
        """Test NestedPowerPort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.nested_power_port.NestedPowerPort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
