# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.rack_group import RackGroup  # noqa: E501
from aionetbox.rest import ApiException


class TestRackGroup(unittest.TestCase):
    """RackGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRackGroup(self):
        """Test RackGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.rack_group.RackGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
