# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.virtual_machine_interface import VirtualMachineInterface  # noqa: E501
from aionetbox.rest import ApiException


class TestVirtualMachineInterface(unittest.TestCase):
    """VirtualMachineInterface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVirtualMachineInterface(self):
        """Test VirtualMachineInterface"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.virtual_machine_interface.VirtualMachineInterface()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
