# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.interface_connection import InterfaceConnection  # noqa: E501
from aionetbox.rest import ApiException


class TestInterfaceConnection(unittest.TestCase):
    """InterfaceConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInterfaceConnection(self):
        """Test InterfaceConnection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.interface_connection.InterfaceConnection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
