# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.api.tenancy_api import TenancyApi  # noqa: E501
from aionetbox.rest import ApiException


class TestTenancyApi(unittest.TestCase):
    """TenancyApi unit test stubs"""

    def setUp(self):
        self.api = aionetbox.api.tenancy_api.TenancyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenancy_choices_list(self):
        """Test case for tenancy_choices_list

        """
        pass

    def test_tenancy_choices_read(self):
        """Test case for tenancy_choices_read

        """
        pass

    def test_tenancy_tenant_groups_create(self):
        """Test case for tenancy_tenant_groups_create

        """
        pass

    def test_tenancy_tenant_groups_delete(self):
        """Test case for tenancy_tenant_groups_delete

        """
        pass

    def test_tenancy_tenant_groups_list(self):
        """Test case for tenancy_tenant_groups_list

        """
        pass

    def test_tenancy_tenant_groups_partial_update(self):
        """Test case for tenancy_tenant_groups_partial_update

        """
        pass

    def test_tenancy_tenant_groups_read(self):
        """Test case for tenancy_tenant_groups_read

        """
        pass

    def test_tenancy_tenant_groups_update(self):
        """Test case for tenancy_tenant_groups_update

        """
        pass

    def test_tenancy_tenants_create(self):
        """Test case for tenancy_tenants_create

        """
        pass

    def test_tenancy_tenants_delete(self):
        """Test case for tenancy_tenants_delete

        """
        pass

    def test_tenancy_tenants_list(self):
        """Test case for tenancy_tenants_list

        """
        pass

    def test_tenancy_tenants_partial_update(self):
        """Test case for tenancy_tenants_partial_update

        """
        pass

    def test_tenancy_tenants_read(self):
        """Test case for tenancy_tenants_read

        """
        pass

    def test_tenancy_tenants_update(self):
        """Test case for tenancy_tenants_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
