# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.rear_port import RearPort  # noqa: E501
from aionetbox.rest import ApiException


class TestRearPort(unittest.TestCase):
    """RearPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRearPort(self):
        """Test RearPort"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.rear_port.RearPort()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
