# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.inline_response20043 import InlineResponse20043  # noqa: E501
from aionetbox.rest import ApiException


class TestInlineResponse20043(unittest.TestCase):
    """InlineResponse20043 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20043(self):
        """Test InlineResponse20043"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.inline_response20043.InlineResponse20043()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
