# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.aggregate import Aggregate  # noqa: E501
from aionetbox.rest import ApiException


class TestAggregate(unittest.TestCase):
    """Aggregate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregate(self):
        """Test Aggregate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.aggregate.Aggregate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
