# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.nested_vlan import NestedVLAN  # noqa: E501
from aionetbox.rest import ApiException


class TestNestedVLAN(unittest.TestCase):
    """NestedVLAN unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNestedVLAN(self):
        """Test NestedVLAN"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.nested_vlan.NestedVLAN()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
