# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.circuit_termination import CircuitTermination  # noqa: E501
from aionetbox.rest import ApiException


class TestCircuitTermination(unittest.TestCase):
    """CircuitTermination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCircuitTermination(self):
        """Test CircuitTermination"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.circuit_termination.CircuitTermination()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
