# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.api.ipam_api import IpamApi  # noqa: E501
from aionetbox.rest import ApiException


class TestIpamApi(unittest.TestCase):
    """IpamApi unit test stubs"""

    def setUp(self):
        self.api = aionetbox.api.ipam_api.IpamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ipam_aggregates_create(self):
        """Test case for ipam_aggregates_create

        """
        pass

    def test_ipam_aggregates_delete(self):
        """Test case for ipam_aggregates_delete

        """
        pass

    def test_ipam_aggregates_list(self):
        """Test case for ipam_aggregates_list

        """
        pass

    def test_ipam_aggregates_partial_update(self):
        """Test case for ipam_aggregates_partial_update

        """
        pass

    def test_ipam_aggregates_read(self):
        """Test case for ipam_aggregates_read

        """
        pass

    def test_ipam_aggregates_update(self):
        """Test case for ipam_aggregates_update

        """
        pass

    def test_ipam_choices_list(self):
        """Test case for ipam_choices_list

        """
        pass

    def test_ipam_choices_read(self):
        """Test case for ipam_choices_read

        """
        pass

    def test_ipam_ip_addresses_create(self):
        """Test case for ipam_ip_addresses_create

        """
        pass

    def test_ipam_ip_addresses_delete(self):
        """Test case for ipam_ip_addresses_delete

        """
        pass

    def test_ipam_ip_addresses_list(self):
        """Test case for ipam_ip_addresses_list

        """
        pass

    def test_ipam_ip_addresses_partial_update(self):
        """Test case for ipam_ip_addresses_partial_update

        """
        pass

    def test_ipam_ip_addresses_read(self):
        """Test case for ipam_ip_addresses_read

        """
        pass

    def test_ipam_ip_addresses_update(self):
        """Test case for ipam_ip_addresses_update

        """
        pass

    def test_ipam_prefixes_available_ips_create(self):
        """Test case for ipam_prefixes_available_ips_create

        """
        pass

    def test_ipam_prefixes_available_ips_read(self):
        """Test case for ipam_prefixes_available_ips_read

        """
        pass

    def test_ipam_prefixes_available_prefixes_create(self):
        """Test case for ipam_prefixes_available_prefixes_create

        """
        pass

    def test_ipam_prefixes_available_prefixes_read(self):
        """Test case for ipam_prefixes_available_prefixes_read

        """
        pass

    def test_ipam_prefixes_create(self):
        """Test case for ipam_prefixes_create

        """
        pass

    def test_ipam_prefixes_delete(self):
        """Test case for ipam_prefixes_delete

        """
        pass

    def test_ipam_prefixes_list(self):
        """Test case for ipam_prefixes_list

        """
        pass

    def test_ipam_prefixes_partial_update(self):
        """Test case for ipam_prefixes_partial_update

        """
        pass

    def test_ipam_prefixes_read(self):
        """Test case for ipam_prefixes_read

        """
        pass

    def test_ipam_prefixes_update(self):
        """Test case for ipam_prefixes_update

        """
        pass

    def test_ipam_rirs_create(self):
        """Test case for ipam_rirs_create

        """
        pass

    def test_ipam_rirs_delete(self):
        """Test case for ipam_rirs_delete

        """
        pass

    def test_ipam_rirs_list(self):
        """Test case for ipam_rirs_list

        """
        pass

    def test_ipam_rirs_partial_update(self):
        """Test case for ipam_rirs_partial_update

        """
        pass

    def test_ipam_rirs_read(self):
        """Test case for ipam_rirs_read

        """
        pass

    def test_ipam_rirs_update(self):
        """Test case for ipam_rirs_update

        """
        pass

    def test_ipam_roles_create(self):
        """Test case for ipam_roles_create

        """
        pass

    def test_ipam_roles_delete(self):
        """Test case for ipam_roles_delete

        """
        pass

    def test_ipam_roles_list(self):
        """Test case for ipam_roles_list

        """
        pass

    def test_ipam_roles_partial_update(self):
        """Test case for ipam_roles_partial_update

        """
        pass

    def test_ipam_roles_read(self):
        """Test case for ipam_roles_read

        """
        pass

    def test_ipam_roles_update(self):
        """Test case for ipam_roles_update

        """
        pass

    def test_ipam_services_create(self):
        """Test case for ipam_services_create

        """
        pass

    def test_ipam_services_delete(self):
        """Test case for ipam_services_delete

        """
        pass

    def test_ipam_services_list(self):
        """Test case for ipam_services_list

        """
        pass

    def test_ipam_services_partial_update(self):
        """Test case for ipam_services_partial_update

        """
        pass

    def test_ipam_services_read(self):
        """Test case for ipam_services_read

        """
        pass

    def test_ipam_services_update(self):
        """Test case for ipam_services_update

        """
        pass

    def test_ipam_vlan_groups_create(self):
        """Test case for ipam_vlan_groups_create

        """
        pass

    def test_ipam_vlan_groups_delete(self):
        """Test case for ipam_vlan_groups_delete

        """
        pass

    def test_ipam_vlan_groups_list(self):
        """Test case for ipam_vlan_groups_list

        """
        pass

    def test_ipam_vlan_groups_partial_update(self):
        """Test case for ipam_vlan_groups_partial_update

        """
        pass

    def test_ipam_vlan_groups_read(self):
        """Test case for ipam_vlan_groups_read

        """
        pass

    def test_ipam_vlan_groups_update(self):
        """Test case for ipam_vlan_groups_update

        """
        pass

    def test_ipam_vlans_create(self):
        """Test case for ipam_vlans_create

        """
        pass

    def test_ipam_vlans_delete(self):
        """Test case for ipam_vlans_delete

        """
        pass

    def test_ipam_vlans_list(self):
        """Test case for ipam_vlans_list

        """
        pass

    def test_ipam_vlans_partial_update(self):
        """Test case for ipam_vlans_partial_update

        """
        pass

    def test_ipam_vlans_read(self):
        """Test case for ipam_vlans_read

        """
        pass

    def test_ipam_vlans_update(self):
        """Test case for ipam_vlans_update

        """
        pass

    def test_ipam_vrfs_create(self):
        """Test case for ipam_vrfs_create

        """
        pass

    def test_ipam_vrfs_delete(self):
        """Test case for ipam_vrfs_delete

        """
        pass

    def test_ipam_vrfs_list(self):
        """Test case for ipam_vrfs_list

        """
        pass

    def test_ipam_vrfs_partial_update(self):
        """Test case for ipam_vrfs_partial_update

        """
        pass

    def test_ipam_vrfs_read(self):
        """Test case for ipam_vrfs_read

        """
        pass

    def test_ipam_vrfs_update(self):
        """Test case for ipam_vrfs_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
