# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.vlan import VLAN  # noqa: E501
from aionetbox.rest import ApiException


class TestVLAN(unittest.TestCase):
    """VLAN unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVLAN(self):
        """Test VLAN"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.vlan.VLAN()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
