# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.models.inline_response20051 import InlineResponse20051  # noqa: E501
from aionetbox.rest import ApiException


class TestInlineResponse20051(unittest.TestCase):
    """InlineResponse20051 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20051(self):
        """Test InlineResponse20051"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aionetbox.models.inline_response20051.InlineResponse20051()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
