# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import aionetbox
from aionetbox.api.dcim_api import DcimApi  # noqa: E501
from aionetbox.rest import ApiException


class TestDcimApi(unittest.TestCase):
    """DcimApi unit test stubs"""

    def setUp(self):
        self.api = aionetbox.api.dcim_api.DcimApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dcim_cables_create(self):
        """Test case for dcim_cables_create

        """
        pass

    def test_dcim_cables_delete(self):
        """Test case for dcim_cables_delete

        """
        pass

    def test_dcim_cables_list(self):
        """Test case for dcim_cables_list

        """
        pass

    def test_dcim_cables_partial_update(self):
        """Test case for dcim_cables_partial_update

        """
        pass

    def test_dcim_cables_read(self):
        """Test case for dcim_cables_read

        """
        pass

    def test_dcim_cables_update(self):
        """Test case for dcim_cables_update

        """
        pass

    def test_dcim_choices_list(self):
        """Test case for dcim_choices_list

        """
        pass

    def test_dcim_choices_read(self):
        """Test case for dcim_choices_read

        """
        pass

    def test_dcim_connected_device_list(self):
        """Test case for dcim_connected_device_list

        """
        pass

    def test_dcim_console_connections_list(self):
        """Test case for dcim_console_connections_list

        """
        pass

    def test_dcim_console_port_templates_create(self):
        """Test case for dcim_console_port_templates_create

        """
        pass

    def test_dcim_console_port_templates_delete(self):
        """Test case for dcim_console_port_templates_delete

        """
        pass

    def test_dcim_console_port_templates_list(self):
        """Test case for dcim_console_port_templates_list

        """
        pass

    def test_dcim_console_port_templates_partial_update(self):
        """Test case for dcim_console_port_templates_partial_update

        """
        pass

    def test_dcim_console_port_templates_read(self):
        """Test case for dcim_console_port_templates_read

        """
        pass

    def test_dcim_console_port_templates_update(self):
        """Test case for dcim_console_port_templates_update

        """
        pass

    def test_dcim_console_ports_create(self):
        """Test case for dcim_console_ports_create

        """
        pass

    def test_dcim_console_ports_delete(self):
        """Test case for dcim_console_ports_delete

        """
        pass

    def test_dcim_console_ports_list(self):
        """Test case for dcim_console_ports_list

        """
        pass

    def test_dcim_console_ports_partial_update(self):
        """Test case for dcim_console_ports_partial_update

        """
        pass

    def test_dcim_console_ports_read(self):
        """Test case for dcim_console_ports_read

        """
        pass

    def test_dcim_console_ports_trace(self):
        """Test case for dcim_console_ports_trace

        """
        pass

    def test_dcim_console_ports_update(self):
        """Test case for dcim_console_ports_update

        """
        pass

    def test_dcim_console_server_port_templates_create(self):
        """Test case for dcim_console_server_port_templates_create

        """
        pass

    def test_dcim_console_server_port_templates_delete(self):
        """Test case for dcim_console_server_port_templates_delete

        """
        pass

    def test_dcim_console_server_port_templates_list(self):
        """Test case for dcim_console_server_port_templates_list

        """
        pass

    def test_dcim_console_server_port_templates_partial_update(self):
        """Test case for dcim_console_server_port_templates_partial_update

        """
        pass

    def test_dcim_console_server_port_templates_read(self):
        """Test case for dcim_console_server_port_templates_read

        """
        pass

    def test_dcim_console_server_port_templates_update(self):
        """Test case for dcim_console_server_port_templates_update

        """
        pass

    def test_dcim_console_server_ports_create(self):
        """Test case for dcim_console_server_ports_create

        """
        pass

    def test_dcim_console_server_ports_delete(self):
        """Test case for dcim_console_server_ports_delete

        """
        pass

    def test_dcim_console_server_ports_list(self):
        """Test case for dcim_console_server_ports_list

        """
        pass

    def test_dcim_console_server_ports_partial_update(self):
        """Test case for dcim_console_server_ports_partial_update

        """
        pass

    def test_dcim_console_server_ports_read(self):
        """Test case for dcim_console_server_ports_read

        """
        pass

    def test_dcim_console_server_ports_trace(self):
        """Test case for dcim_console_server_ports_trace

        """
        pass

    def test_dcim_console_server_ports_update(self):
        """Test case for dcim_console_server_ports_update

        """
        pass

    def test_dcim_device_bay_templates_create(self):
        """Test case for dcim_device_bay_templates_create

        """
        pass

    def test_dcim_device_bay_templates_delete(self):
        """Test case for dcim_device_bay_templates_delete

        """
        pass

    def test_dcim_device_bay_templates_list(self):
        """Test case for dcim_device_bay_templates_list

        """
        pass

    def test_dcim_device_bay_templates_partial_update(self):
        """Test case for dcim_device_bay_templates_partial_update

        """
        pass

    def test_dcim_device_bay_templates_read(self):
        """Test case for dcim_device_bay_templates_read

        """
        pass

    def test_dcim_device_bay_templates_update(self):
        """Test case for dcim_device_bay_templates_update

        """
        pass

    def test_dcim_device_bays_create(self):
        """Test case for dcim_device_bays_create

        """
        pass

    def test_dcim_device_bays_delete(self):
        """Test case for dcim_device_bays_delete

        """
        pass

    def test_dcim_device_bays_list(self):
        """Test case for dcim_device_bays_list

        """
        pass

    def test_dcim_device_bays_partial_update(self):
        """Test case for dcim_device_bays_partial_update

        """
        pass

    def test_dcim_device_bays_read(self):
        """Test case for dcim_device_bays_read

        """
        pass

    def test_dcim_device_bays_update(self):
        """Test case for dcim_device_bays_update

        """
        pass

    def test_dcim_device_roles_create(self):
        """Test case for dcim_device_roles_create

        """
        pass

    def test_dcim_device_roles_delete(self):
        """Test case for dcim_device_roles_delete

        """
        pass

    def test_dcim_device_roles_list(self):
        """Test case for dcim_device_roles_list

        """
        pass

    def test_dcim_device_roles_partial_update(self):
        """Test case for dcim_device_roles_partial_update

        """
        pass

    def test_dcim_device_roles_read(self):
        """Test case for dcim_device_roles_read

        """
        pass

    def test_dcim_device_roles_update(self):
        """Test case for dcim_device_roles_update

        """
        pass

    def test_dcim_device_types_create(self):
        """Test case for dcim_device_types_create

        """
        pass

    def test_dcim_device_types_delete(self):
        """Test case for dcim_device_types_delete

        """
        pass

    def test_dcim_device_types_list(self):
        """Test case for dcim_device_types_list

        """
        pass

    def test_dcim_device_types_partial_update(self):
        """Test case for dcim_device_types_partial_update

        """
        pass

    def test_dcim_device_types_read(self):
        """Test case for dcim_device_types_read

        """
        pass

    def test_dcim_device_types_update(self):
        """Test case for dcim_device_types_update

        """
        pass

    def test_dcim_devices_create(self):
        """Test case for dcim_devices_create

        """
        pass

    def test_dcim_devices_delete(self):
        """Test case for dcim_devices_delete

        """
        pass

    def test_dcim_devices_graphs(self):
        """Test case for dcim_devices_graphs

        """
        pass

    def test_dcim_devices_list(self):
        """Test case for dcim_devices_list

        """
        pass

    def test_dcim_devices_napalm(self):
        """Test case for dcim_devices_napalm

        """
        pass

    def test_dcim_devices_partial_update(self):
        """Test case for dcim_devices_partial_update

        """
        pass

    def test_dcim_devices_read(self):
        """Test case for dcim_devices_read

        """
        pass

    def test_dcim_devices_update(self):
        """Test case for dcim_devices_update

        """
        pass

    def test_dcim_front_port_templates_create(self):
        """Test case for dcim_front_port_templates_create

        """
        pass

    def test_dcim_front_port_templates_delete(self):
        """Test case for dcim_front_port_templates_delete

        """
        pass

    def test_dcim_front_port_templates_list(self):
        """Test case for dcim_front_port_templates_list

        """
        pass

    def test_dcim_front_port_templates_partial_update(self):
        """Test case for dcim_front_port_templates_partial_update

        """
        pass

    def test_dcim_front_port_templates_read(self):
        """Test case for dcim_front_port_templates_read

        """
        pass

    def test_dcim_front_port_templates_update(self):
        """Test case for dcim_front_port_templates_update

        """
        pass

    def test_dcim_front_ports_create(self):
        """Test case for dcim_front_ports_create

        """
        pass

    def test_dcim_front_ports_delete(self):
        """Test case for dcim_front_ports_delete

        """
        pass

    def test_dcim_front_ports_list(self):
        """Test case for dcim_front_ports_list

        """
        pass

    def test_dcim_front_ports_partial_update(self):
        """Test case for dcim_front_ports_partial_update

        """
        pass

    def test_dcim_front_ports_read(self):
        """Test case for dcim_front_ports_read

        """
        pass

    def test_dcim_front_ports_update(self):
        """Test case for dcim_front_ports_update

        """
        pass

    def test_dcim_interface_connections_list(self):
        """Test case for dcim_interface_connections_list

        """
        pass

    def test_dcim_interface_templates_create(self):
        """Test case for dcim_interface_templates_create

        """
        pass

    def test_dcim_interface_templates_delete(self):
        """Test case for dcim_interface_templates_delete

        """
        pass

    def test_dcim_interface_templates_list(self):
        """Test case for dcim_interface_templates_list

        """
        pass

    def test_dcim_interface_templates_partial_update(self):
        """Test case for dcim_interface_templates_partial_update

        """
        pass

    def test_dcim_interface_templates_read(self):
        """Test case for dcim_interface_templates_read

        """
        pass

    def test_dcim_interface_templates_update(self):
        """Test case for dcim_interface_templates_update

        """
        pass

    def test_dcim_interfaces_create(self):
        """Test case for dcim_interfaces_create

        """
        pass

    def test_dcim_interfaces_delete(self):
        """Test case for dcim_interfaces_delete

        """
        pass

    def test_dcim_interfaces_graphs(self):
        """Test case for dcim_interfaces_graphs

        """
        pass

    def test_dcim_interfaces_list(self):
        """Test case for dcim_interfaces_list

        """
        pass

    def test_dcim_interfaces_partial_update(self):
        """Test case for dcim_interfaces_partial_update

        """
        pass

    def test_dcim_interfaces_read(self):
        """Test case for dcim_interfaces_read

        """
        pass

    def test_dcim_interfaces_trace(self):
        """Test case for dcim_interfaces_trace

        """
        pass

    def test_dcim_interfaces_update(self):
        """Test case for dcim_interfaces_update

        """
        pass

    def test_dcim_inventory_items_create(self):
        """Test case for dcim_inventory_items_create

        """
        pass

    def test_dcim_inventory_items_delete(self):
        """Test case for dcim_inventory_items_delete

        """
        pass

    def test_dcim_inventory_items_list(self):
        """Test case for dcim_inventory_items_list

        """
        pass

    def test_dcim_inventory_items_partial_update(self):
        """Test case for dcim_inventory_items_partial_update

        """
        pass

    def test_dcim_inventory_items_read(self):
        """Test case for dcim_inventory_items_read

        """
        pass

    def test_dcim_inventory_items_update(self):
        """Test case for dcim_inventory_items_update

        """
        pass

    def test_dcim_manufacturers_create(self):
        """Test case for dcim_manufacturers_create

        """
        pass

    def test_dcim_manufacturers_delete(self):
        """Test case for dcim_manufacturers_delete

        """
        pass

    def test_dcim_manufacturers_list(self):
        """Test case for dcim_manufacturers_list

        """
        pass

    def test_dcim_manufacturers_partial_update(self):
        """Test case for dcim_manufacturers_partial_update

        """
        pass

    def test_dcim_manufacturers_read(self):
        """Test case for dcim_manufacturers_read

        """
        pass

    def test_dcim_manufacturers_update(self):
        """Test case for dcim_manufacturers_update

        """
        pass

    def test_dcim_platforms_create(self):
        """Test case for dcim_platforms_create

        """
        pass

    def test_dcim_platforms_delete(self):
        """Test case for dcim_platforms_delete

        """
        pass

    def test_dcim_platforms_list(self):
        """Test case for dcim_platforms_list

        """
        pass

    def test_dcim_platforms_partial_update(self):
        """Test case for dcim_platforms_partial_update

        """
        pass

    def test_dcim_platforms_read(self):
        """Test case for dcim_platforms_read

        """
        pass

    def test_dcim_platforms_update(self):
        """Test case for dcim_platforms_update

        """
        pass

    def test_dcim_power_connections_list(self):
        """Test case for dcim_power_connections_list

        """
        pass

    def test_dcim_power_feeds_create(self):
        """Test case for dcim_power_feeds_create

        """
        pass

    def test_dcim_power_feeds_delete(self):
        """Test case for dcim_power_feeds_delete

        """
        pass

    def test_dcim_power_feeds_list(self):
        """Test case for dcim_power_feeds_list

        """
        pass

    def test_dcim_power_feeds_partial_update(self):
        """Test case for dcim_power_feeds_partial_update

        """
        pass

    def test_dcim_power_feeds_read(self):
        """Test case for dcim_power_feeds_read

        """
        pass

    def test_dcim_power_feeds_update(self):
        """Test case for dcim_power_feeds_update

        """
        pass

    def test_dcim_power_outlet_templates_create(self):
        """Test case for dcim_power_outlet_templates_create

        """
        pass

    def test_dcim_power_outlet_templates_delete(self):
        """Test case for dcim_power_outlet_templates_delete

        """
        pass

    def test_dcim_power_outlet_templates_list(self):
        """Test case for dcim_power_outlet_templates_list

        """
        pass

    def test_dcim_power_outlet_templates_partial_update(self):
        """Test case for dcim_power_outlet_templates_partial_update

        """
        pass

    def test_dcim_power_outlet_templates_read(self):
        """Test case for dcim_power_outlet_templates_read

        """
        pass

    def test_dcim_power_outlet_templates_update(self):
        """Test case for dcim_power_outlet_templates_update

        """
        pass

    def test_dcim_power_outlets_create(self):
        """Test case for dcim_power_outlets_create

        """
        pass

    def test_dcim_power_outlets_delete(self):
        """Test case for dcim_power_outlets_delete

        """
        pass

    def test_dcim_power_outlets_list(self):
        """Test case for dcim_power_outlets_list

        """
        pass

    def test_dcim_power_outlets_partial_update(self):
        """Test case for dcim_power_outlets_partial_update

        """
        pass

    def test_dcim_power_outlets_read(self):
        """Test case for dcim_power_outlets_read

        """
        pass

    def test_dcim_power_outlets_trace(self):
        """Test case for dcim_power_outlets_trace

        """
        pass

    def test_dcim_power_outlets_update(self):
        """Test case for dcim_power_outlets_update

        """
        pass

    def test_dcim_power_panels_create(self):
        """Test case for dcim_power_panels_create

        """
        pass

    def test_dcim_power_panels_delete(self):
        """Test case for dcim_power_panels_delete

        """
        pass

    def test_dcim_power_panels_list(self):
        """Test case for dcim_power_panels_list

        """
        pass

    def test_dcim_power_panels_partial_update(self):
        """Test case for dcim_power_panels_partial_update

        """
        pass

    def test_dcim_power_panels_read(self):
        """Test case for dcim_power_panels_read

        """
        pass

    def test_dcim_power_panels_update(self):
        """Test case for dcim_power_panels_update

        """
        pass

    def test_dcim_power_port_templates_create(self):
        """Test case for dcim_power_port_templates_create

        """
        pass

    def test_dcim_power_port_templates_delete(self):
        """Test case for dcim_power_port_templates_delete

        """
        pass

    def test_dcim_power_port_templates_list(self):
        """Test case for dcim_power_port_templates_list

        """
        pass

    def test_dcim_power_port_templates_partial_update(self):
        """Test case for dcim_power_port_templates_partial_update

        """
        pass

    def test_dcim_power_port_templates_read(self):
        """Test case for dcim_power_port_templates_read

        """
        pass

    def test_dcim_power_port_templates_update(self):
        """Test case for dcim_power_port_templates_update

        """
        pass

    def test_dcim_power_ports_create(self):
        """Test case for dcim_power_ports_create

        """
        pass

    def test_dcim_power_ports_delete(self):
        """Test case for dcim_power_ports_delete

        """
        pass

    def test_dcim_power_ports_list(self):
        """Test case for dcim_power_ports_list

        """
        pass

    def test_dcim_power_ports_partial_update(self):
        """Test case for dcim_power_ports_partial_update

        """
        pass

    def test_dcim_power_ports_read(self):
        """Test case for dcim_power_ports_read

        """
        pass

    def test_dcim_power_ports_trace(self):
        """Test case for dcim_power_ports_trace

        """
        pass

    def test_dcim_power_ports_update(self):
        """Test case for dcim_power_ports_update

        """
        pass

    def test_dcim_rack_groups_create(self):
        """Test case for dcim_rack_groups_create

        """
        pass

    def test_dcim_rack_groups_delete(self):
        """Test case for dcim_rack_groups_delete

        """
        pass

    def test_dcim_rack_groups_list(self):
        """Test case for dcim_rack_groups_list

        """
        pass

    def test_dcim_rack_groups_partial_update(self):
        """Test case for dcim_rack_groups_partial_update

        """
        pass

    def test_dcim_rack_groups_read(self):
        """Test case for dcim_rack_groups_read

        """
        pass

    def test_dcim_rack_groups_update(self):
        """Test case for dcim_rack_groups_update

        """
        pass

    def test_dcim_rack_reservations_create(self):
        """Test case for dcim_rack_reservations_create

        """
        pass

    def test_dcim_rack_reservations_delete(self):
        """Test case for dcim_rack_reservations_delete

        """
        pass

    def test_dcim_rack_reservations_list(self):
        """Test case for dcim_rack_reservations_list

        """
        pass

    def test_dcim_rack_reservations_partial_update(self):
        """Test case for dcim_rack_reservations_partial_update

        """
        pass

    def test_dcim_rack_reservations_read(self):
        """Test case for dcim_rack_reservations_read

        """
        pass

    def test_dcim_rack_reservations_update(self):
        """Test case for dcim_rack_reservations_update

        """
        pass

    def test_dcim_rack_roles_create(self):
        """Test case for dcim_rack_roles_create

        """
        pass

    def test_dcim_rack_roles_delete(self):
        """Test case for dcim_rack_roles_delete

        """
        pass

    def test_dcim_rack_roles_list(self):
        """Test case for dcim_rack_roles_list

        """
        pass

    def test_dcim_rack_roles_partial_update(self):
        """Test case for dcim_rack_roles_partial_update

        """
        pass

    def test_dcim_rack_roles_read(self):
        """Test case for dcim_rack_roles_read

        """
        pass

    def test_dcim_rack_roles_update(self):
        """Test case for dcim_rack_roles_update

        """
        pass

    def test_dcim_racks_create(self):
        """Test case for dcim_racks_create

        """
        pass

    def test_dcim_racks_delete(self):
        """Test case for dcim_racks_delete

        """
        pass

    def test_dcim_racks_list(self):
        """Test case for dcim_racks_list

        """
        pass

    def test_dcim_racks_partial_update(self):
        """Test case for dcim_racks_partial_update

        """
        pass

    def test_dcim_racks_read(self):
        """Test case for dcim_racks_read

        """
        pass

    def test_dcim_racks_units(self):
        """Test case for dcim_racks_units

        """
        pass

    def test_dcim_racks_update(self):
        """Test case for dcim_racks_update

        """
        pass

    def test_dcim_rear_port_templates_create(self):
        """Test case for dcim_rear_port_templates_create

        """
        pass

    def test_dcim_rear_port_templates_delete(self):
        """Test case for dcim_rear_port_templates_delete

        """
        pass

    def test_dcim_rear_port_templates_list(self):
        """Test case for dcim_rear_port_templates_list

        """
        pass

    def test_dcim_rear_port_templates_partial_update(self):
        """Test case for dcim_rear_port_templates_partial_update

        """
        pass

    def test_dcim_rear_port_templates_read(self):
        """Test case for dcim_rear_port_templates_read

        """
        pass

    def test_dcim_rear_port_templates_update(self):
        """Test case for dcim_rear_port_templates_update

        """
        pass

    def test_dcim_rear_ports_create(self):
        """Test case for dcim_rear_ports_create

        """
        pass

    def test_dcim_rear_ports_delete(self):
        """Test case for dcim_rear_ports_delete

        """
        pass

    def test_dcim_rear_ports_list(self):
        """Test case for dcim_rear_ports_list

        """
        pass

    def test_dcim_rear_ports_partial_update(self):
        """Test case for dcim_rear_ports_partial_update

        """
        pass

    def test_dcim_rear_ports_read(self):
        """Test case for dcim_rear_ports_read

        """
        pass

    def test_dcim_rear_ports_update(self):
        """Test case for dcim_rear_ports_update

        """
        pass

    def test_dcim_regions_create(self):
        """Test case for dcim_regions_create

        """
        pass

    def test_dcim_regions_delete(self):
        """Test case for dcim_regions_delete

        """
        pass

    def test_dcim_regions_list(self):
        """Test case for dcim_regions_list

        """
        pass

    def test_dcim_regions_partial_update(self):
        """Test case for dcim_regions_partial_update

        """
        pass

    def test_dcim_regions_read(self):
        """Test case for dcim_regions_read

        """
        pass

    def test_dcim_regions_update(self):
        """Test case for dcim_regions_update

        """
        pass

    def test_dcim_sites_create(self):
        """Test case for dcim_sites_create

        """
        pass

    def test_dcim_sites_delete(self):
        """Test case for dcim_sites_delete

        """
        pass

    def test_dcim_sites_graphs(self):
        """Test case for dcim_sites_graphs

        """
        pass

    def test_dcim_sites_list(self):
        """Test case for dcim_sites_list

        """
        pass

    def test_dcim_sites_partial_update(self):
        """Test case for dcim_sites_partial_update

        """
        pass

    def test_dcim_sites_read(self):
        """Test case for dcim_sites_read

        """
        pass

    def test_dcim_sites_update(self):
        """Test case for dcim_sites_update

        """
        pass

    def test_dcim_virtual_chassis_create(self):
        """Test case for dcim_virtual_chassis_create

        """
        pass

    def test_dcim_virtual_chassis_delete(self):
        """Test case for dcim_virtual_chassis_delete

        """
        pass

    def test_dcim_virtual_chassis_list(self):
        """Test case for dcim_virtual_chassis_list

        """
        pass

    def test_dcim_virtual_chassis_partial_update(self):
        """Test case for dcim_virtual_chassis_partial_update

        """
        pass

    def test_dcim_virtual_chassis_read(self):
        """Test case for dcim_virtual_chassis_read

        """
        pass

    def test_dcim_virtual_chassis_update(self):
        """Test case for dcim_virtual_chassis_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
