# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DeviceRole(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'slug': 'str',
        'color': 'str',
        'vm_role': 'bool',
        'device_count': 'int',
        'virtualmachine_count': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'slug': 'slug',
        'color': 'color',
        'vm_role': 'vm_role',
        'device_count': 'device_count',
        'virtualmachine_count': 'virtualmachine_count'
    }

    def __init__(self, id=None, name=None, slug=None, color=None, vm_role=None, device_count=None, virtualmachine_count=None):  # noqa: E501
        """DeviceRole - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._slug = None
        self._color = None
        self._vm_role = None
        self._device_count = None
        self._virtualmachine_count = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.name = name
        self.slug = slug
        self.color = color
        if vm_role is not None:
            self.vm_role = vm_role
        if device_count is not None:
            self.device_count = device_count
        if virtualmachine_count is not None:
            self.virtualmachine_count = virtualmachine_count

    @property
    def id(self):
        """Gets the id of this DeviceRole.  # noqa: E501


        :return: The id of this DeviceRole.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DeviceRole.


        :param id: The id of this DeviceRole.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this DeviceRole.  # noqa: E501


        :return: The name of this DeviceRole.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeviceRole.


        :param name: The name of this DeviceRole.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 50:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `50`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this DeviceRole.  # noqa: E501


        :return: The slug of this DeviceRole.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this DeviceRole.


        :param slug: The slug of this DeviceRole.  # noqa: E501
        :type: str
        """
        if slug is None:
            raise ValueError("Invalid value for `slug`, must not be `None`")  # noqa: E501
        if slug is not None and len(slug) > 50:
            raise ValueError("Invalid value for `slug`, length must be less than or equal to `50`")  # noqa: E501
        if slug is not None and len(slug) < 1:
            raise ValueError("Invalid value for `slug`, length must be greater than or equal to `1`")  # noqa: E501
        if slug is not None and not re.search(r'^[-a-zA-Z0-9_]+$', slug):  # noqa: E501
            raise ValueError(r"Invalid value for `slug`, must be a follow pattern or equal to `/^[-a-zA-Z0-9_]+$/`")  # noqa: E501

        self._slug = slug

    @property
    def color(self):
        """Gets the color of this DeviceRole.  # noqa: E501


        :return: The color of this DeviceRole.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this DeviceRole.


        :param color: The color of this DeviceRole.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501
        if color is not None and len(color) > 6:
            raise ValueError("Invalid value for `color`, length must be less than or equal to `6`")  # noqa: E501
        if color is not None and len(color) < 1:
            raise ValueError("Invalid value for `color`, length must be greater than or equal to `1`")  # noqa: E501
        if color is not None and not re.search(r'^[0-9a-f]{6}$', color):  # noqa: E501
            raise ValueError(r"Invalid value for `color`, must be a follow pattern or equal to `/^[0-9a-f]{6}$/`")  # noqa: E501

        self._color = color

    @property
    def vm_role(self):
        """Gets the vm_role of this DeviceRole.  # noqa: E501

        Virtual machines may be assigned to this role  # noqa: E501

        :return: The vm_role of this DeviceRole.  # noqa: E501
        :rtype: bool
        """
        return self._vm_role

    @vm_role.setter
    def vm_role(self, vm_role):
        """Sets the vm_role of this DeviceRole.

        Virtual machines may be assigned to this role  # noqa: E501

        :param vm_role: The vm_role of this DeviceRole.  # noqa: E501
        :type: bool
        """

        self._vm_role = vm_role

    @property
    def device_count(self):
        """Gets the device_count of this DeviceRole.  # noqa: E501


        :return: The device_count of this DeviceRole.  # noqa: E501
        :rtype: int
        """
        return self._device_count

    @device_count.setter
    def device_count(self, device_count):
        """Sets the device_count of this DeviceRole.


        :param device_count: The device_count of this DeviceRole.  # noqa: E501
        :type: int
        """

        self._device_count = device_count

    @property
    def virtualmachine_count(self):
        """Gets the virtualmachine_count of this DeviceRole.  # noqa: E501


        :return: The virtualmachine_count of this DeviceRole.  # noqa: E501
        :rtype: int
        """
        return self._virtualmachine_count

    @virtualmachine_count.setter
    def virtualmachine_count(self, virtualmachine_count):
        """Sets the virtualmachine_count of this DeviceRole.


        :param virtualmachine_count: The virtualmachine_count of this DeviceRole.  # noqa: E501
        :type: int
        """

        self._virtualmachine_count = virtualmachine_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceRole, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceRole):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
