# coding: utf-8

"""
    NetBox API

    API to access NetBox  # noqa: E501

    OpenAPI spec version: 2.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from aionetbox.models.nested_device_type import NestedDeviceType  # noqa: F401,E501
from aionetbox.models.status import Status  # noqa: F401,E501


class InterfaceTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'device_type': 'NestedDeviceType',
        'name': 'str',
        'type': 'Status',
        'form_factor': 'Status',
        'mgmt_only': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'device_type': 'device_type',
        'name': 'name',
        'type': 'type',
        'form_factor': 'form_factor',
        'mgmt_only': 'mgmt_only'
    }

    def __init__(self, id=None, device_type=None, name=None, type=None, form_factor=None, mgmt_only=None):  # noqa: E501
        """InterfaceTemplate - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._device_type = None
        self._name = None
        self._type = None
        self._form_factor = None
        self._mgmt_only = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.device_type = device_type
        self.name = name
        if type is not None:
            self.type = type
        if form_factor is not None:
            self.form_factor = form_factor
        if mgmt_only is not None:
            self.mgmt_only = mgmt_only

    @property
    def id(self):
        """Gets the id of this InterfaceTemplate.  # noqa: E501


        :return: The id of this InterfaceTemplate.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InterfaceTemplate.


        :param id: The id of this InterfaceTemplate.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def device_type(self):
        """Gets the device_type of this InterfaceTemplate.  # noqa: E501


        :return: The device_type of this InterfaceTemplate.  # noqa: E501
        :rtype: NestedDeviceType
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this InterfaceTemplate.


        :param device_type: The device_type of this InterfaceTemplate.  # noqa: E501
        :type: NestedDeviceType
        """
        if device_type is None:
            raise ValueError("Invalid value for `device_type`, must not be `None`")  # noqa: E501

        self._device_type = device_type

    @property
    def name(self):
        """Gets the name of this InterfaceTemplate.  # noqa: E501


        :return: The name of this InterfaceTemplate.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InterfaceTemplate.


        :param name: The name of this InterfaceTemplate.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 64:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this InterfaceTemplate.  # noqa: E501


        :return: The type of this InterfaceTemplate.  # noqa: E501
        :rtype: Status
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InterfaceTemplate.


        :param type: The type of this InterfaceTemplate.  # noqa: E501
        :type: Status
        """

        self._type = type

    @property
    def form_factor(self):
        """Gets the form_factor of this InterfaceTemplate.  # noqa: E501


        :return: The form_factor of this InterfaceTemplate.  # noqa: E501
        :rtype: Status
        """
        return self._form_factor

    @form_factor.setter
    def form_factor(self, form_factor):
        """Sets the form_factor of this InterfaceTemplate.


        :param form_factor: The form_factor of this InterfaceTemplate.  # noqa: E501
        :type: Status
        """

        self._form_factor = form_factor

    @property
    def mgmt_only(self):
        """Gets the mgmt_only of this InterfaceTemplate.  # noqa: E501


        :return: The mgmt_only of this InterfaceTemplate.  # noqa: E501
        :rtype: bool
        """
        return self._mgmt_only

    @mgmt_only.setter
    def mgmt_only(self, mgmt_only):
        """Sets the mgmt_only of this InterfaceTemplate.


        :param mgmt_only: The mgmt_only of this InterfaceTemplate.  # noqa: E501
        :type: bool
        """

        self._mgmt_only = mgmt_only

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InterfaceTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InterfaceTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
